from fastapi.testclient import TestClient


class TestViews:
    def test_create_user_error(self, client: TestClient): ...
    def test_create_user_success(self, client: TestClient): ...
    def test_retrieve_user_by_username_error(self, client: TestClient): ...
    def test_retrieve_user_by_username_success(self, client: TestClient): ...
